### ISSUE TITLE
publish on CRAN?

### ISSUE THREAD

**Issue by nick-youngblut** [cmmr/rbiom#1]
The rbiom repo contains a `cran-comments.md` file, but it's not published on CRAN. What is the timeline for publishing it on CRAN? Is this project dead (ie., should users find another package that is or will be on CRAN)?

**Comment by dansmith01** [comment]
I've been holding off on submitting rbiom to CRAN until the code gets to a point where I feel the code is pretty stable. It's probably ready to go now. Thanks for the reminder!

**Comment by nick-youngblut** [comment]
Thanks for the quick response and also for creating a UniFrac implementation in R that is rather fast and doesn't have questionable results like `phyloseq`
