### ISSUE TITLE
Grey Screen

### ISSUE THREAD

**Issue by akbrand6** [cmmr/rbiom#15]
## description
I have been using Atima through Baylor College of Medicine for ~6 months now without issue. But about a week ago I went to log in and the screen just went grey. I can close and open atima as many times I want, but the screen just stays grey. I can open it in incognito and it works, until I try to log in. But as soon I try to log in it just goes grey again.  I cleared my cookies, and that allowed me to the website again without it staying grey...... until I tried to log in, then I am right back to where I started. It seems to be an issue with my account.  There are no popups.

## detail
There is one weird detail about this whole thing that's hard to explain, so i've included a picture. When the screen is grey, I can still see behind the gray? it's very weird. I can even click around. But there are no pop-ups.  I do not have pop-up blocker enabled, it's just a transparent grey, but nothing loads either.  

![image](https://github.com/cmmr/rbiom/assets/139649010/1c8685f1-319f-44e3-af25-d566218f1bfe)

I tried to click everything you can see, and nothing works.  Very very weirdly, When I 'select project' I can click 'Upload Private Dataset and it opens my file explorer like its almost working, but once I select a file I can't do anything with it, it just stays grey.

Any help is appreciated.

Thank you!

**Comment by dansmith01** [comment]
Hi @akbrand6, atima defaults to the last project you viewed, which may be crashing each time it tries to open it. Try using a direct link to a different project, such as: https://atima.research.bcm.edu/?p=3317

**Comment by akbrand6** [comment]
Thank you, but that still didn't quite work.  That allows me to go to the intro page. But as soon as I try to log in it just goes grey again.  Any ideas why that would be and how to overcome that?

Thank you again!

**Comment by dansmith01** [comment]
I deleted I think was the offending project - can you try logging in now?
