### ISSUE TITLE
Is there a way to add a title to ordinal plots

### ISSUE THREAD

**Issue by shwetha141** [cmmr/rbiom#17]
1.)  As the title suggests, is there a way to add a title to each UMAP other than the caption option that specifies the method?

For eg. I have multiple umaps across a wide range of phenotypes that need to be presented by a variable, making it easier to identify.

**Comment by dansmith01** [comment]
The ggplot2 functions `ggtitle()` and `labs()` can help you here. rbiom's *_plot() functions all return a ggplot2 object, so you can do things like:
`p <- bdiv_ord_plot(...) + ggplot2::ggtitle("Custom Title", "Custom Subtitle")`

**Comment by shwetha141** [comment]
Got it. thank you :)
