### ISSUE TITLE
Unifrac: Error: OTUs missing from reference tree

### ISSUE THREAD

**Issue by colin-heberling** [cmmr/rbiom#3]
What exactly does this mean?  That there are OTUs in my matrix that are not represented in my phylogenetic tree?  With my particular use case I find this hard to believe, and maybe I'm not using the package as intended, so I'd like to get some clarity on that.

I downloaded the bacterial tree from GTDB, which lists all ~30k bacterial representative reference genomes in GTDB using their NCBI accession IDs.  My OTU table has NCBI accessions in the first column, and relative abundance values for each sample in the remaining columns.  I had a row that couldn't match an accession ('NA') which I removed, thinking that would solve the issue, but I'm still having the same issue.  I mapped the original OTUs to the GTDB representative NCBI accessions from the GTDB metadata, so there shouldn't be any accessions in my OTU table that are missing from the tree.

Might it be useful to add a new feature so that any OTUs encountered that are not present within the reference tree would be treated as branches outside the provided tree so that computation can continue without crashing?

**Comment by colin-heberling** [comment]
I'm getting a different error locally, there's something wrong with the tree tip ids.
```
> unifrac_unw = unifrac(as.matrix(pa_k5_core_spread), weighted=FALSE, tree = bac_tree)
Error: Tips must be given as character, logical, or numeric.
```
I tried your commands and it looks like nothing is matching, possibly because the tip ids seem to be read into the tree incorrectly: it's removing the underscores.
```
> bac_tree

Phylogenetic tree with 45555 tips and 45554 internal nodes.

Tip labels:
  RS GCF 001020875.1, RS GCF 902498005.1, RS GCF 014472415.1, RS GCF 002813455.1, RS GCF 009764645.1, RS GCF 000282515.1, ...
Node labels:
  d  Bacteria, 65.0, 100.0, 10.0, 10.0, 1.0, ...

Rooted; includes branch lengths.
> otus = rbiom::taxa.names(as.matrix(pa_k5_core_spread))
Error: In taxa.names(), biom must be a BIOM-class object.
> otus = pa_k5_core_spread$Organism_Name
> present = otus %in% rbiom::tips(bac_tree)
> table(present)
present
FALSE 
  258 
> otus[present]
character(0)
> head(otus[!present])
[1] "GB_GCA_000210015.1" "GB_GCA_000210075.1" "GB_GCA_001312445.1" "GB_GCA_002160535.1" "GB_GCA_003477405.1"
[6] "GB_GCA_008661915.1"
```
Do you have any advice on getting the tree to be read in my desired format?  Could you provide any explanation to the new error I'm getting?

**Comment by dansmith01** [comment]
Thanks for that information. I understand what's happening now. I coded rbiom's newick parser to convert underscores in unquoted identifiers to spaces, as per the spec at https://evolution.genetics.washington.edu/phylip/newicktree.html . I'll need to reexamine that decision though if it's doing more harm than good.

For now though, a quick fix would be one of the following:

1: Read the tree using ape::read.tree() in lieu of rbiom::read.tree(). ape's version doesn't convert underscores and its returned phylo object is compatible with rbiom.

2: Add the underscores back into the phylo object's tip names.
```r
bac_tree$tip.label <- gsub(" ", "_", bac_tree$tip.label)
```

Let me know if these suggestions work. I'll adjust rbiom::read.tree to handle underscores differently going forward. And thank you for the bug report!

**Comment by colin-heberling** [comment]
That appears to have fixed that problem, but now after removing the remaining offending OTUs, I'm still left with another error:

```
Phylogenetic tree with 45555 tips and 45554 internal nodes.

Tip labels:
  RS_GCF_001020875.1, RS_GCF_902498005.1, RS_GCF_014472415.1, RS_GCF_002813455.1, RS_GCF_009764645.1, RS_GCF_000282515.1, ...
Node labels:
  d  Bacteria, 65.0, 100.0, 10.0, 10.0, 1.0, ...

Rooted; includes branch lengths.
present
FALSE  TRUE 
    2   255 
[1] "GB_GCA_000210015.1" "GB_GCA_000210075.1" "GB_GCA_001312445.1"
[4] "GB_GCA_002160535.1" "GB_GCA_003477405.1" "GB_GCA_008661915.1"
[1] "RS_GCF_000016525.1" "RS_GCF_002252585.1"
[1] "after filtering missing OTUs from reference: "
present
TRUE 
 255 
[1] "GB_GCA_000210015.1" "GB_GCA_000210075.1" "GB_GCA_001312445.1"
[4] "GB_GCA_002160535.1" "GB_GCA_003477405.1" "GB_GCA_008661915.1"
character(0)
Error in par_unifrac(counts, tree, ifelse(weighted, 1L, 0L)) : 
  Not compatible with requested type: [type=character; target=double].
Calls: unifrac -> <Anonymous> -> par_unifrac
Execution halted
```
Is there an issue with my matrix format?  It is not an rbiom object, and the values are not read counts, I'm using either presence/absence (1 or 0) or CLR-transformed relative abundance values.

Also, for some reason I haven't been able to successfully read this tree with ape, because it thinks the parentheses are unbalanced, so I've had to use rbiom to read the tree.

**Comment by dansmith01** [comment]
This error message is something I haven't encountered before:
```
Error in par_unifrac(counts, tree, ifelse(weighted, 1L, 0L)) : 
  Not compatible with requested type: [type=character; target=double].
```

It could be that something is being passed in as character where numeric is expected.

Can you show me the output from the following commands?
```r
mtx <- as.matrix(pa_k5_core_spread)
class(mtx)
any(is.na(mtx))
range(colSums(mtx))
range(rowSums(mtx))
head(rownames(mtx))
head(colnames(mtx))

v <- slam::as.simple_triplet_matrix(mtx)[['v']]
class(v)
any(is.na(v))
range(v)

class(bac_tree$edge.length)
any(is.na(bac_tree$edge.length))
range(bac_tree$edge.length)
```

**Comment by colin-heberling** [comment]
```
> mtx = as.matrix(pa_k5_core_spread)
> class(mtx)
[1] "matrix" "array" 
> all(is.finite(mtx))
[1] FALSE
> range(colSums(mtx))
Error in colSums(mtx) : 'x' must be numeric
> range(rowSums(mtx))
Error in rowSums(mtx) : 'x' must be numeric
> head(rownames(mtx))
NULL
> head(colnames(mtx))
[1] "Organism_Name" "BC000100"      "BC000101"      "BC000102"      "BC000103"      "BC000104"     
> v <- slam::as.simple_triplet_matrix(mtx)[['v']]
> class(v)
[1] "character"
> all(is.finite(v))
[1] FALSE
> range(v)
[1] "0"     "X.NA."
> class(bac_tree$edge.length)
[1] "numeric"
> all(is.finite(bac_tree$edge.length))
[1] TRUE
> range(bac_tree$edge.length)
[1] 0.0005 1.9046
```

**Comment by dansmith01** [comment]
Converting the matrix to numeric should get things working. Move the organism names to the row names, drop the organism names column, then convert the matrix using as.numeric().

I’m on mobile at the moment, but I’ll update this comment with some code once I’ve got a keyboard, unless you’re able to get it working before then.

**Comment by dansmith01** [comment]
Something like this oughta do it:

```r
mtx <- as.matrix(pa_k5_core_spread)
rownames(mtx) <- mtx[,1]
mtx <- mtx[,-1]
mtx[] <- as.numeric(mtx)
dm <- rbiom::unifrac(mtx, tree = bac_tree)
```

**Comment by colin-heberling** [comment]
Got it working, thanks so much!  Removing the otu id column did the trick.
